### ISSUE TITLE
Failed to add multiple products

### ISSUE THREAD

**Issue by ajeetkumarrauniyar** [ajeetkumarrauniyar/StockTrack#1]
- Unable to add multiple products using the CSV upload feature on first attempt. 
- Error message: "Failed to add multiple products
- Multiple products are updated in the UI and uploaded after a page refresh.

### Steps to Reproduce:

1. Navigate to the "Products" section.
2. Click on the "Choose file" button and select a valid CSV file.
3. Click on the "Upload CSV" button.

### Expected Behavior:

- The application should successfully add the products from the CSV file.

Actual Behavior:

- An error message appears indicating that the products could not be added.

### Possible Causes:

- An issue with the CSV file format or data.
- A bug in the product upload logic.

### Screenshots:
![after upload csv](https://github.com/user-attachments/assets/55476c73-bd33-4052-915b-aaf07f0bd6c5)

**Comment by InderParmar** [comment]
Hi, I am interested in working on this issue, can you please assign this issue to me? Thanks.

**Comment by ajeetkumarrauniyar** [comment]
Hi, @InderParmar Are you working on the issue?

**Comment by InderParmar** [comment]
Hi @ajeetkumarrauniyar , yes I am working on the issue, will update you soon, can you comment here your discord or slack username? If I have any questions I can sent it there.

**Comment by ajeetkumarrauniyar** [comment]
Hi @InderParmar PFA link of the [Discord's Server](https://discord.gg/cjetBYdZ). Please use the dedicated Issues Channel.
